# Base config file for bountylink

log_level: DEBUG
user_agent: # custom user agent or empty

# Wildcards don't work for now
paths: # Paths for individual programs, can also be just a name if the executable/script is in $PATH
  amass:
  amass_config: # path to config or empty
  massdns:
  shuffledns:
  subdomain_wordlist:
  dns_resolvers: # use https://github.com/vortexau/dnsvalidator to generate
  httpx:
  eyewitness:
  takeover:
  availableforpurchase:
  webanalyze:
  corsy:
  gau:
  gitleaks:
  cloudflair:
  naabu:
